name: diaspora_mobile
description: "A Flutter mobile app for Diaspora e-Commerce."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^1.0.8

  # HTTP requests
  http: ^1.1.0

  # Navigation
  go_router: ^16.2.4
  
  # Stockage sécurisé (pour token si besoin futur)
  flutter_secure_storage: ^9.0.1

  # Toast messages
  fluttertoast: ^8.2.1

  # State management (facultatif si besoin)
  provider: ^6.0.5

  # Images et assets
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/